server:
  port: 8090
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/v1/user/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        # USER-SERVICE commands
        - id: users-command-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/login, /api/v1/user/register
            - Method=POST
          filters:
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable

        # SOCIAL-SERVICE commands
        - id: social-command-route
          uri: lb://social-service
          predicates:
            - Path=/api/v1/social/friend-request/**,
            - Method=POST
          filters:
            - TokenRelay  # For adding the jwt to the request
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable

          # SOCIAL-SERVICE queries
        - id: social-queries-route
          uri: lb://social-service
          predicates:
            - Path=/api/v1/social/friend-request,
            - Method=GET
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: queryResilienceConfig
                fallbackUri: forward:/fallback/query-unavailable

          # FEED-SERVICE (CQRS)
        - id: feed-queries-route
          uri: lb://feed-service
          predicates:
            - Path=/api/v1/feed/**,
            - Method=GET
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: queryResilienceConfig
                fallbackUri: forward:/fallback/query-unavailable

        # POST-SERVICE commands
        - id: post-command-route
          uri: lb://post-service
          predicates:
            - Path=/api/v1/post/**,
            - Method=POST, DELETE
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable

# ---------------------------------------------------------
# Resilience config
# ---------------------------------------------------------
resilience4j:

  # CIRCUIT BREAKER
  circuitbreaker:
    instances:
      queryResilienceConfig:
        slidingWindowSize: 20
        failureRateThreshold: 40
        waitDurationInOpenState: 5s
      commandResilienceConfig:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  # TIME LIMITER
  timelimiter:
    instances:
      queryResilienceConfig:
        timeoutDuration: 1s
      commandResilienceConfig:
        timeoutDuration: 3s

# ---------------------------------------------------------
# Eureka Configuration
# ---------------------------------------------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}