app:
  routes:
    user:
      host: ${USER_SVC_URL:http://localhost:8081}
      auth: "/api/v1/user/login, /api/v1/user/register"
      base: "/api/v1/user/**"
    social:
      host: ${SOCIAL_SVC_URL:http://localhost:8082}
      auth: "/api/v1/social/friend-request/**"
      base: "/api/v1/social/friend-request"
    post:
      host: ${POST_SVC_URL:http://localhost:8083}
      base: "/api/v1/post/**"
    feed:
      host: ${FEED_SVC_URL:http://localhost:8084}
      base: "/api/v1/feed/**"

x-config:
  rate-limits:
    command: &commandRateLimit
      redis-rate-limiter.replenishRate: 2
      redis-rate-limiter.burstCapacity: 5
      redis-rate-limiter.requestedTokens: 1
      key-resolver: "#{@userKeyResolver}"
    query: &queryRateLimit
      redis-rate-limiter.replenishRate: 10
      redis-rate-limiter.burstCapacity: 20
      redis-rate-limiter.requestedTokens: 1
      key-resolver: "#{@userKeyResolver}"

server:
  port: 8089

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/v1/user/.well-known/jwks.json

  cloud:
    gateway:
      routes:
        # --- User Service ---
        - id: users-command-route
          uri: ${app.routes.user.host}  # <--- Reference to host variable
          predicates:
            - Path=${app.routes.user.auth}
            - Method=POST
          filters:
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable
            - name: RequestRateLimiter
              args: *commandRateLimit

        # --- Social Service (Command) ---
        - id: social-command-route
          uri: ${app.routes.social.host}  # <--- Reference to host variable
          predicates:
            - Path=${app.routes.social.auth}
            - Method=POST
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable
            - name: RequestRateLimiter
              args: *commandRateLimit

        # --- Social Service (Query) ---
        - id: social-queries-route
          uri: ${app.routes.social.host}  # <--- Reference to host variable
          predicates:
            - Path=${app.routes.social.base}
            - Method=GET
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: queryResilienceConfig
                fallbackUri: forward:/fallback/query-unavailable
            - name: RequestRateLimiter
              args: *queryRateLimit

        # --- Feed Service ---
        - id: feed-queries-route
          uri: ${app.routes.feed.host}  # <--- Reference to host variable
          predicates:
            - Path=${app.routes.feed.base}
            - Method=GET
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: queryResilienceConfig
                fallbackUri: forward:/fallback/query-unavailable
            - name: RequestRateLimiter
              args: *queryRateLimit

        # --- Post Service ---
        - id: post-command-route
          uri: ${app.routes.post.host}  # <--- Reference to host variable
          predicates:
            - Path=${app.routes.post.base}
            - Method=POST, DELETE
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable
            - name: RequestRateLimiter
              args: *commandRateLimit

resilience4j:
  circuitbreaker:
    instances:
      queryResilienceConfig:
        slidingWindowSize: 20
        failureRateThreshold: 40
        waitDurationInOpenState: 5s
      commandResilienceConfig:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      queryResilienceConfig:
        timeoutDuration: 1s
      commandResilienceConfig:
        timeoutDuration: 3s