x-config:
  rate-limits:
    command: &commandRateLimit
      redis-rate-limiter.replenishRate: 2
      redis-rate-limiter.burstCapacity: 5
      redis-rate-limiter.requestedTokens: 1
      key-resolver: "#{@userKeyResolver}"
    query: &queryRateLimit
      redis-rate-limiter.replenishRate: 10
      redis-rate-limiter.burstCapacity: 20
      redis-rate-limiter.requestedTokens: 1
      key-resolver: "#{@userKeyResolver}"

server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: ${SPRING_APP_NAME:api-gateway}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  cloud:
    gateway:
      routes:
        - id: users-command-route
          uri: ${USER_SVC_URL}
          predicates:
            - Path=/api/v1/user/login, /api/v1/user/register
            - Method=POST
          filters:
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable
            - name: RequestRateLimiter
              args: *commandRateLimit

        - id: social-command-route
          uri: ${SOCIAL_SVC_URL}
          predicates:
            - Path=/api/v1/social/friend-request/**
            - Method=POST
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable
            - name: RequestRateLimiter
              args: *commandRateLimit

        - id: social-queries-route
          uri: ${SOCIAL_SVC_URL}
          predicates:
            - Path=/api/v1/social/friend-request
            - Method=GET
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: queryResilienceConfig
                fallbackUri: forward:/fallback/query-unavailable
            - name: RequestRateLimiter
              args: *queryRateLimit

        - id: feed-queries-route
          uri: ${FEED_SVC_URL}
          predicates:
            - Path=/api/v1/feed/**
            - Method=GET
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: queryResilienceConfig
                fallbackUri: forward:/fallback/query-unavailable
            - name: RequestRateLimiter
              args: *queryRateLimit

        - id: post-command-route
          uri: ${POST_SVC_URL}
          predicates:
            - Path=/api/v1/post/**
            - Method=POST, DELETE
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: commandResilienceConfig
                fallbackUri: forward:/fallback/command-unavailable
            - name: RequestRateLimiter
              args: *commandRateLimit

resilience4j:
  circuitbreaker:
    instances:
      queryResilienceConfig:
        slidingWindowSize: 20
        failureRateThreshold: 40
        waitDurationInOpenState: 5s
      commandResilienceConfig:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      queryResilienceConfig:
        timeoutDuration: 1s
      commandResilienceConfig:
        timeoutDuration: 3s
