apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: gaze-app
  labels:
    app: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: juangmz7/notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"     # Request 0.1 CPU
              memory: "256Mi"
            limits:
              cpu: "500m"    # Set CPU limit in 0.2
              memory: "512Mi"

          # --- App configuration ---
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SERVER_PORT

            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SPRING_APP_NAME

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: INFRA_DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: INFRA_DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: NOTIFICATION_DB_NAME

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: NOTIFICATION_DB_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: notification-db-password

            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: mail-username

            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: mail-password

            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: INFRA_RABBIT_HOST

            - name: SPRING_MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: MAIL_HOST

            - name: SPRING_MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: MAIL_PORT