apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: gaze-app
data:
  SERVER_PORT: "8080"
  SPRING_APP_NAME: "notification-service"

  INFRA_DB_HOST: "postgres.infra.svc.cluster.local"
  INFRA_DB_PORT: "5432"
  INFRA_RABBIT_HOST: "rabbitmq.infra.svc.cluster.local"

  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"

  NOTIFICATION_DB_NAME: "notification_db"
  NOTIFICATION_DB_USER: "notif_user"
