apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gaze-application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: feed-service
            path: infra/k8s/apps/feed-service

          - name: post-service
            path: infra/k8s/apps/post-service

          - name: gateway-service
            path: infra/k8s/apps/gateway-api

          - name: notification-service
            path: infra/k8s/apps/notification-service

          - name: social-service
            path: infra/k8s/apps/social-service

          - name: user-service
            path: infra/k8s/apps/user-service

  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Juangmz7/Gaze-app.git'
        targetRevision: test
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: gaze-app

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true