apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: gaze-app
data:
  SERVER_PORT: "8080"
  SPRING_APP_NAME: "api-gateway"

  # Service URIs
  USER_SVC_URL: "http://user-service.infra.svc.cluster.local:8080"
  SOCIAL_SVC_URL: "http://social-service.infra.svc.cluster.local:8080"
  FEED_SVC_URL: "http://feed-service.infra.svc.cluster.local:8080"
  POST_SVC_URL: "http://post-service.infra.svc.cluster.local:8080"

  # Security
  JWK_SET_URI: "http://user-service.infra.svc.cluster.local:8080/api/v1/user/.well-known/jwks.json"