apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: gaze-app
  labels:
    app: feed-service
spec:
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: juangmz7/feed-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"     # Request 0.1 CPU
              memory: "256Mi"
            limits:
              cpu: "500m"    # Set CPU limit in 0.2
              memory: "512Mi"