apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaze-app
resources:
  - 00-deployment.yaml
  - 01-service.yaml
  - 02-scaled-object.yaml
  - config.yaml
  - ../../common/rabbitmq-auth.yaml