apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: gaze-app
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          volumeMounts:
            - name: secret-volume
              mountPath: "/app/certs"
              readOnly: true
            - name: public-key-volume
              mountPath: "/app/certs/public"
              readOnly: true
          image: juangmz7/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # --- App configuration ---
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SERVER_PORT

            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SPRING_APP_NAME

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: INFRA_DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: INFRA_DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: USER_DB_NAME

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: USER_DB_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: user-db-password

            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: INFRA_RABBIT_HOST

            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: rabbitmq-password

            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: RABBITMQ_USERNAME

            - name: JWT_KEYS_PRIVATE_PATH
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: JWT_PRIVATE_KEY_PATH

            - name: JWT_KEYS_PUBLIC_PATH
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: JWT_PUBLIC_KEY_PATH

      volumes:
        - name: secret-volume
          secret:
            secretName: jwt-keys
        - name: public-key-volume
          secret:
            secretName: jwt-public-key