apiVersion: v1
kind: ConfigMap
metadata:
  name: social-config
  namespace: gaze-app
data:
  SERVER_PORT: "8080"
  SPRING_APP_NAME: "social-service"

  INFRA_DB_HOST: "postgres.infra.svc.cluster.local"
  INFRA_DB_PORT: "5432"
  INFRA_RABBIT_HOST: "rabbitmq.infra.svc.cluster.local"

  SOCIAL_DB_NAME: "social_db"
  SOCIAL_DB_USER: "social_user"

  AUTH_JWK_URI: "http://user-service.gaze-app.svc.cluster.local:8080/api/v1/user/.well-known/jwks.json"