apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config
  namespace: gaze-app
data:
  SERVER_PORT: "8080"
  SPRING_APP_NAME: "post-service"

  INFRA_DB_HOST: "postgres.infra.svc.cluster.local"
  INFRA_DB_PORT: "5432"
  INFRA_RABBIT_HOST: "rabbitmq.infra.svc.cluster.local"

  POST_DB_NAME: "post_db"
  POST_DB_USER: "post_user"

  RABBITMQ_USERNAME: admin-user

  AUTH_JWK_URI: "http://user-service.gaze-app.svc.cluster.local:8080/api/v1/user/.well-known/jwks.json"