apiVersion: v2
name: postgres-wrapper
description: Wrapper for Gaze App Postgres
type: application
version: 1.0.0
dependencies:
  - name: postgresql
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami